controller_ansible_config_dir: /etc/ansible
controller_ansible_passwd_path: "{{ controller_ansible_config_dir }}/hypernova-ansible-passwd"
controller_secret_dir: "/home/{{ controller_ansible_user }}/secret"
controller_public_dir: "/home/{{ controller_ansible_user }}/public_html"
controller_hypernova_ansible_path: "/home/{{ controller_ansible_user }}/hypernova-ansible"
controller_ansible_user: ansible
controller_playbook_repo: "https://github.com/Hypernova-Oy/hypernova-ansible.git"
